name: win32_registry
description: A set of helper classes for working with the Windows registry.
version: 1.2.0
repository: https://github.com/timsneath/win32_registry
issue_tracker: https://github.com/timsneath/win32_registry/issues

environment:
  sdk: '>=2.17.0 <4.0.0'

platforms:
  windows:

dependencies:
  ffi: ^2.0.0
  rxdart: ^0.27.0
  win32: ^4.1.1
  compute: 1.0.2

dev_dependencies:
  lints: ^2.0.1
  test: ^1.23.1
